### ISSUE TITLE
Environment variable 'jwt_secret_key' is not defined

### ISSUE THREAD

**Issue by cichy** [simpletut/Universal-React-Redux-Registration#1]
How to define jwt never done this before and I'm getting error =>
Error: Environment variable \'jwt_secret_key\' is not defined

**Comment by simpletut** [comment]
As you have closed this issue, I am going to assume you have figured it out. 

In order to verify a users 'token' we have to decode and compare it will a secret key that is stored on the server side.

To ensure that the Key is not stored within our written code or ever checked in (by mistake), we define this as an environment variable.

As a result, you need to define this variable before you attempt to run the app. You will also need to ensure you have defined upon deployment.

For more information, please see our documentation: [Link](https://simpletut.gitbook.io/universal-react-redux-registration/set-up-the-backend#node-environment-variables)

**Comment by simpletut** [comment]
As you have closed this issue, I am going to assume you have figured it out.

For those that might want more information, in order to verify a user's 'token' we have to compare it with a secret key that is stored on the server.

For the best practice and security reasons the key is not stored within our code. Instead we set it as a node environment variable.

As a result you will need to define this variable before you attempt to run the app. You will also need to ensure you have defined upon deployment.

For more information, please see our documentation: [Link](https://simpletut.gitbook.io/universal-react-redux-registration/set-up-the-backend#node-environment-variables)
